### ISSUE TITLE
Promisified sagas

### ISSUE THREAD

**Issue by mikeqcp** [apptension/cra-template-apptension#33]
Investigate and implement promisified sagas

For example:
https://github.com/adobe/redux-saga-promise
or
https://github.com/afitiskin/redux-saga-routines

It should be used in example `users` module

**Comment by mikeqcp** [comment]
redux-toolkit adds `createAsyncThunk` in `v1.30` (currently in alpha), so we probably would like to refactor this to use it as soon as it gets released

**Comment by mikeqcp** [comment]
[createAsyncThunk](https://redux-toolkit.js.org/api/createAsyncThunk#createasyncthunk) is already out so we can use it already

**Comment by pziemkowski** [comment]
I implemented a redux middleware in typescript similar to https://github.com/adobe/redux-saga-promise

`createAsyncThunk` is really a `redux-thunk` wrapper so not ideal in our case.
